"""Return approval and fines

Revision ID: 5e3434cd5cfa
Revises: 
Create Date: 2025-11-26 20:52:17.281412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e3434cd5cfa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('return_requested', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('returned_at', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('fine_amount', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('fine_amount')
        batch_op.drop_column('returned_at')
        batch_op.drop_column('return_requested')

    # ### end Alembic commands ###
